### ISSUE TITLE
Info log level should log when a MQTT message is published.

### ISSUE THREAD

**Issue by chriscn** [celsworth/lxp-bridge#102]
Would be useful for presentating information. I believe info should log when stuff is sent to MQTT.

**Comment by celsworth** [comment]
Sure I could do that. What would you want to see in the logline? A complete dump of the topic and payload is already logged at DEBUG so presumably not that much information?

The mqtt library I use also logs the topic and payload size, but thats also at DEBUG, so I could replicate something similar to that at INFO level.

**Comment by chriscn** [comment]
What I would find useful is a log file of the following
`{TIME} sent MQTT for inverter {INVERTER}`

I'd been troubleshooting this morning and had to have an MQTT client setup to see when the messages where being sent as oppossed to just tailing the logs.
