### ISSUE TITLE
e_*_day data from inverter can be misleading close to midnight

### ISSUE THREAD

**Issue by lidgaca** [celsworth/lxp-bridge#137]
Due to the fact that the luxpower inverter time-of-day is inaccurate, if the inverter is fast, it may reset the `e_*_day` counters before real midnight. This means that lxp-bridge stores 0.0 for the `e_*_day` data as the last data for a given day.  This is problematic if you're using an influxql  query of the form 

    select last(e_pv_day) as "Solar Yield" from inputs group by time(1d)

to get a daily summary of the solar yield of the array.

However the more I think about this the more difficult it is to work round properly. It would be much better if the inverter were capable of time-syncing (to something ...) properly ! About the best I can think of is the following pseudo code ...

```
if ((time is between 23:55:00 and midnight) AND (all e_*_day data is zero))
    set all e_*_day data to NULL

```
but suspect this may still cause problems at daylight savings switchover. It also assumes that Luxpower HQ will continue to use a 5 mins data collection schedule.

Anyway just wanted you to be aware of this as a potential issue.

-- Chris

**Comment by celsworth** [comment]
Hi!

Thanks for the heads up, yeah this looks like it could be annoying. I have experimented with time syncing to the inverter with some success, but I'd suggest not relying on the `_day` registers at all; how about something like this instead?

```
select spread(e_pv_all) from inputs group by time(1d);
```

This should have the same result I think but without relying on the inverter knowing the time.

**Comment by lidgaca** [comment]
Thanks.

Yes that query gets round the problem. I'm new to influx and grafana, so I'm still learning :)

-- Chris
