### ISSUE TITLE
Set logging levels

### ISSUE THREAD

**Issue by Beenay25** [celsworth/lxp-bridge#141]
I could be completely missing something obvious, but docker, portainer and lxp-bridge are all pretty new to me.

Is there a way to set the logging level for lxp-bridge?

At the moment all the logs I see are full of DEBUG messages. I want to quieten them down a little.

**Comment by celsworth** [comment]
Hi,

Yes there's an environment variable `RUST_LOG` that will be honoured. Set this when starting lxp-bridge.

It's set in the example systemd unit file: https://github.com/celsworth/lxp-bridge/blob/master/systemd/lxp-bridge.service#L9

```
Environment="RUST_LOG=info"
```

I guess a configuration file option for this wouldn't go amiss. And maybe it can be mentioned in the docs, will take a look at adding that.

**Comment by Beenay25** [comment]
Perfect. Thank you so much for the fast response.

I just set an environmental variable up in Portainer and it worked first time.
