### ISSUE TITLE
Current calculations

### ISSUE THREAD

**Issue by Sboshoff76** [celsworth/lxp-bridge#187]
Nothing serious, but seeing as power = voltage x current, do you think you can include some additional sensors that work out the current when the power and voltage is know for a device? A specific use case is solar dashboards that monitor the amps coming in from the solar panels but it could be applied to battery/home/grid usage as well.

I know it can be done in a HA template but figured if it's not too much work it could be done here and your integration could be a bit more noob friendly.

Thanks for listening!

**Comment by celsworth** [comment]
I'm on the fence about this one :) I'm reluctant to add too many extra things to the `inputs` JSON (and Influx, and database rows), especially things that don't directly come from the inverter.

I realise I'm setting a precedent for it by adding the `p_pv` sum, and `p_grid` and `p_battery` etc though.

I think for now stick to doing this in HA templates, and if this gets more requests in future we can revisit it? To anyone else, feel free to add a +1 if you'd want this.

**Comment by Sboshoff76** [comment]
No problem. Thanks for entertaining the idea at least!
