### ISSUE TITLE
Charge Priority not being read correctly

### ISSUE THREAD

**Issue by garthy** [celsworth/lxp-bridge#200]
So my Inverter has charge priority enabled and set to 00:01-05:50

lxp bridge seems to read the time slot correctly but the switch for charge priority is off.

![charge-prio](https://github.com/celsworth/lxp-bridge/assets/1085290/f2fb33bf-1b0e-48ad-9205-d2b4c8e5a59a)

![ha-charge-prio](https://github.com/celsworth/lxp-bridge/assets/1085290/5be6745b-9161-46cc-8949-3294253fb1b2)

My Invertor is a Hybrid 3.6KWh with AAAA-201E firmware (latest as of a few weeks ago)

**Comment by garthy** [comment]
Ah I suspect it's an error in this bit field and this should be 11 not 1  

`            forced_discharge_en: Self::is_bit_set(data, 1 << 10),
            charge_priority_en: Self::is_bit_set(data, 1 << 1),
            iso_en: Self::is_bit_set(data, 1 << 12),`

**Comment by celsworth** [comment]
Ooh, yes - great spot. Thats definitely a typo, looks like it's been broken since the introduction of the `hold/21/bits` message, which the HA autodiscovery message uses. I'll get a fix in for this now.

**Comment by garthy** [comment]
Can  confirm this is fixed in latest version.
