### ISSUE TITLE
Add WriteParam functions

### ISSUE THREAD

**Issue by celsworth** [celsworth/lxp-bridge#22]
This is super low priority because I think it's potentially quite a dangerous operation that nobody should normally need. Improvements were made in #92 to ignore WriteParam packets sent by Luxpower, to avoid lxp-bridge crashing because of them.

From source-code analysis, I *think*:

Param 0 is seconds between automated `inputs` broadcasts
Writing to param 1 sets the datalog serial number
Writing -91 (aka 165?) to param 3 is factory reset

It has been observed that Luxpower are writing 3 registers starting at 7 quite often on some newer inverters, but no idea why or what they are.

**Comment by kaitlinsm** [comment]
Did i read that right - `param 0` is the cadence of publishing the stats from all the sensors in the inverter, and defaults to 5 minutes?

This will publish to both the local interface AND the luxpower server interface, so setting this to a lower value will cause problems with clogging up their servers?

**Comment by celsworth** [comment]
Yes, exactly. When I first got my inverter, this register was set to 120 (2 minutes). Later changed to 3 minutes, then again changed to 5 minutes, so I think they've been decreasing the frequency of all inverters to reduce load on their servers over time.

If you did change this register to a low value then it could be a good idea to firewall your inverter off from their servers so it can't send data back. This would prevent their web interface working with your inverter at all though, of course, including firmware updates etc.. but some people might not think isolating their kit from China is a bad thing anyway :)

It's been on my list for some time to try changing this value, and isolating my own inverter from them, just to see if everything keeps working properly locally, just never got round to it yet.

**Comment by kaitlinsm** [comment]
Yeah, I was aware that these massive chunks of stuff phone home before purchasing one, but kind of "oh well". I've noticed the increased duration between readings too and wasn't surprised, as I think a *lot* of these inverters are being sold in the UK at the moment, at least.

I've had a bit of a read through the code/docs in this repo but I'm not completely familiar with it - can I just confirm something?

In the docs, it seems that publishing 
```
lxp/cmd/{datalog}/read/inputs/1
lxp/cmd/{datalog}/read/inputs/2
lxp/cmd/{datalog}/read/inputs/3
```

should cause every avaiblable sensor value to be published in response, and anyone subscribed to the topics will get the update.

Will this also cause stuff to get sent to china, or is this a local mqtt-driven workaround? basically (sort of bash-esque)

```
while true; do
  mosquitto_pub --topic lxp/cmd/{datalog}/read/inputs/1
  sleep 1
  mosquitto_pub --topic lxp/cmd/{datalog}/read/inputs/2
  sleep 1;
  mosquitto_pub --topic lxp/cmd/{datalog}/read/inputs/3
  sleep 30;
done;
```

**Comment by celsworth** [comment]
Yes that will cause the responses to get sent to China; it's a broadcast system whereby every connection to the inverter sees all the same responses, no matter which connection originally sent the request.

You can probably verify this by publishing those topics then checking the Data History log in the Lux web portal - more than likely they'll log it as an additional data row.

**Comment by kaitlinsm** [comment]
Yep - verified that, that's put an additional data point in place. So doing this in a loop is probably a really bad idea!
