### ISSUE TITLE
Auto start/restart LXP-bridge if no updates for X minutes

### ISSUE THREAD

**Issue by Beenay25** [celsworth/lxp-bridge#222]
I've had a few issues lately where the bridge fails and I don't notice until I spot that the battery hasn't dropped in the evening.

Would it be possible to introduce a feature where the bridge will start/restart if no updates have come in within the last hour?

**Comment by celsworth** [comment]
Yep, this should be possible, I'll see what I can do :)

**Comment by celsworth** [comment]
Do you think it should just reconnect to the inverter or quit the application entirely?

I'm just thinking of multi-inverter setups, usually a reconnect is probably sufficient (if the connection has just gotten stuck). Reconnecting to one inverter doesn't need to interrupt connections to other inverters. But quitting the entire app is a bit nuclear and might interrupt receiving data from a working inverter.

I'll probably just do a single inverter reconnect for now and we can see if that helps first.
