### ISSUE TITLE
Luxpower SNA6000 WPS p_inv=0

### ISSUE THREAD

**Issue by nemirow2** [celsworth/lxp-bridge#236]
Good evening! I can’t figure it out - the inverter load p_inv is always equal to 0, although everything is shown correctly in the application and on the manufacturer’s website - maybe you know what the problem might be?

**Comment by nemirow2** [comment]
I probably explained it wrong - I can’t find in the entities the load consumption from the inverter itself, on the monitoring website it’s called “power consumption” - this is a very important parameter, perhaps this can be done in the home assistant?
So far I've done this:
- platform: template
  sensors:
    power_grid_wat:
      friendly_name: "Power_inv"
      unit_of_measurement: "W"
      device_class: power
      value_template: "  {{(states('sensor.lxp_xxxxxxxxxx_inverter_power') | float)
                          + (states('sensor.lxp_xxxxxxxxxx_grid_power_export_is_negative') | float) 
                           }}"

**Comment by celsworth** [comment]
Is your issue the same as this one? There's some HA code here to calculate consumption: https://github.com/celsworth/lxp-bridge/issues/232

**Comment by nemirow2** [comment]
I see - I just thought that if this parameter is displayed on the inverter display, then here too it can be pulled out without calculations in the home assistant
