### ISSUE TITLE
lxp-bridge reports config to systemd which includes passwords

### ISSUE THREAD

**Issue by zatie12** [celsworth/lxp-bridge#48]
journalctl exposes protected configuration for non privileged users

**Comment by celsworth** [comment]
😱 sorry, left this debugging in by accident, fixed in https://github.com/celsworth/lxp-bridge/commit/1791be884023ca7b6fa06b1ae0cb07382ae5baf0

**Comment by zatie12** [comment]
I may be wrong about the privileged part but it does write the config to the log, including passwords
