### ISSUE TITLE
list of registers

### ISSUE THREAD

**Issue by maegibbons** [celsworth/lxp-bridge#49]
Hi

Thanks for all your hard work on this!

Have you got a list of known registers so that we can see what settings we have access to?

Krs

Mark

**Comment by celsworth** [comment]
Hi :)

Yep! Just added one, see https://github.com/celsworth/lxp-bridge/blob/master/doc/LXP_REGISTERS.txt

It's a bit rough-and-ready as the names are lifted from examining source code but most of them are decipherable I hope :)

I might add a few more explanatory notes to the list if I get some time eventually.
